### ISSUE TITLE
Google Sign in error

### ISSUE THREAD

**Issue by ElangoPrince** [lingonsaft/google-sign-in-expo-create-react-native-app#1]
I'm using Android Emulator:

When i'm trying to click  "Sign in with Google" it say's  **400** Bad request. 
       **Error: Invalid_request**
       Custom scheme URLs are not allowed for 'WEB' client type.
       
       here i attach error image:

![screenshot_20181004-175856](https://user-images.githubusercontent.com/34785789/46474688-1fde8780-c801-11e8-8457-e6a35a512d22.png)

**Comment by BennyCarlsson** [comment]
Hmm might be a problem since you are using an emulator. Tried it on a real android device?

**Comment by ElangoPrince** [comment]
yeah okay thanks.
               Now working fine.

**Comment by BennyCarlsson** [comment]
Great :)

**Comment by ElangoPrince** [comment]
Hi Benny, 
           The expo google API directly open in browser, I'm having gmail application, The API isn't link (open ) to my gmail application.  How to link it my (Gmail) application?
